### PR TITLE
Says&trans flags

### PR DESCRIPTION
**Pull request by Kunde21**
I started by correcting the -says flag to correctly parse a comma-separated list, but I found that the mongodb instance wasn't storing or retrieving as expected.  In an effort to get the -trans flag functioning, I found that the calls to Find() were incorrect and the insert was creating new terms records each time.  The Insert functionality and GetTranslations functionality is now working properly.

### CODE REVIEW

**Comment by aleSuglia** [comment]
Thank you for your effort in trying to fix some incorrect behaviours in my program. I really appreciate it!
Unfortunately, as I've stated in the readme, the project is an early development phase so I expect to find some bugs here and there. In fact, the current version contains only the skeleton of the application that I have in mind.

I'll review the commits that you've done and I'll try to merge them!
Thank you again.

**Comment by Kunde21** [comment]
Not a problem at all.  The fact that this project is early in development was part of the fun.  Plus, I've wanted to learn some MongoDB and this gave me a good opportunity.

**Comment by aleSuglia** [comment]
It's the same reason for which I've started this project. I'm really happy about that. If you want to continue to collaborate, please feel free to extend the program as you desire!

At the moment, I'm studying for a university exam so I'm pretty busy and this is another reason that doesn't grant to me the possibility to complete the project!
Anyway, I'll added you to G+, so we can talk there if you want :)

**Comment by Kunde21** [comment]
Good luck with your exam!  I have a couple more weeks before classes start, so I'll probably be coding more in that time.

**Pull request merged**
